# Generated by Django 3.2.2 on 2021-05-19 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Training title"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="The date and time training starts",
                        verbose_name="Start time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="The date and time training ends",
                        verbose_name="End time",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("slug", models.SlugField(unique_for_date="start_time")),
            ],
            options={
                "ordering": ("-start_time", "end_time"),
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("surname", models.CharField(max_length=255, verbose_name="Surname")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=100, verbose_name="Street and number of a building"
                    ),
                ),
                (
                    "post_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "consent_1",
                    models.BooleanField(
                        default=False,
                        help_text="\n        Consent to the processing of the personal data \n        in a way that is necessary for training realization.",
                        verbose_name="*",
                    ),
                ),
                (
                    "consent_2",
                    models.BooleanField(
                        default=False,
                        help_text="\n        Consent to granting the third party access to the personal data \n        in a way that is necessary for training realization.",
                        verbose_name="*",
                    ),
                ),
                (
                    "consent_3",
                    models.BooleanField(
                        default=False,
                        help_text="\n        Consent to granting the third party access to the personal data \n        in terms of my participation in the exam.",
                        verbose_name="*",
                    ),
                ),
                ("is_finished", models.BooleanField(default=False)),
                ("email_confirmed", models.BooleanField(default=False)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        related_query_name="consent",
                        to="core.training",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Data",
                "verbose_name_plural": "Personal Data",
            },
        ),
    ]
